---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distribution wat
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
            mode: "0644"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib if primary URL fails
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            mode: "0644"
    - name: Install clickhouse packages (.x86_64)
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm
          - clickhouse-client-{{ clickhouse_version }}.x86_64.rpm
          - clickhouse-server-{{ clickhouse_version }}.x86_64.rpm
      notify: Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
- name: Install and Configure Vector
  hosts: clickhouse
  handlers:
    - name: Restart vector
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted

  tasks:
    - name: Download Vector distributive
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/latest/vector-{{ vector_version }}.x86_64.rpm"
        dest: "./vector-{{ vector_version }}.x86_64.rpm"
        mode: "0644"

    - name: Install Vector
      become: true
      ansible.builtin.yum:
        name: "./vector-{{ vector_version }}.x86_64.rpm"
      notify: Restart vector

    - name: Deploy Vector Configuration
      ansible.builtin.template:
        src: vector_config.j2
        dest: ./vector.toml
        mode: "0644"
      notify: Restart vector
- name: Install and Configure LightHouse
  hosts: lighthouse
  pre_tasks:
    - name: Nginx | Install epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: Nginx | Install nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: Nginx | Configure
      become: true
      ansible.builtin.template:
        src: nginx_config.j2
        dest: /etc/nginx/conf.d/lighthouse.conf
        mode: "0644"
  tasks:
    - name: LightHouse | Install
      become: true
      ansible.builtin.yum:
        name: git
        state: present
    - name: LightHouse | Clone repository
      become: true
      ansible.builtin.git:
        repo: '{{ lighthouse_git }}'
        dest: '{{ lighthouse_root_path }}'
        version: master
    - name: Nginx | Start
      become: true
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
