---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 158.160.59.16
    jenkins-agent-01:
      ansible_host: 158.160.102.133
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: aleksei