node("agent"){
    stage("Git checkout"){
        git credentialsId: '6fd13941-6578-4171-b39c-9df007d49cac', url: 'git@github.com:JustAleksy/clickhouse.git'
    }
     stage('Install molecule') {
        steps{
            sh 'pip3 install -r requirements.txt'
            sh "echo ========"
        }
    }
    stage('Run Molecule'){
        steps{
            sh 'molecule test'
            cleanWs()
        }
    }
}