#cloud-config
datasource:
 Ec2:
  strict_id: false
ssh_pwauth: no
users:
- name: aleksei
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKSxXCcIm/hEnkX6ZqEkMApb3IkChWW32e1MlYmvnwXL aleksei@PC
runcmd: []