apiVersion: v1
kind: Pod
metadata:
  name: echoserver-pod # Увидел название hello-world из задания только после того как начал оформлять README.md, лень менять :-P
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080
