---
- name: Установка Java
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Добавление ключа Jenkins
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Добавление репозитория Jenkins
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Установка Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Запуск и включение Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes

