---
# tasks file for roles/grafana
- name: install gpg
  apt:
    name: gnupg,software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Copy GPG key to remote server
  copy:
    src: "/home/aleksei/study/netology/monitoring_and_logs/grafana/gpg-key.txt"
    dest: "/tmp/gpg-key.txt"
    owner: aleksei
    group: root
    mode: '0644'

- name: add gpg key from local file
  apt_key:
    file: "{{ local_gpg_key_path }}"
  when: use_local_gpg_key | bool

- name: add gpg key from remote url
  apt_key:
    url: "{{ remote_gpg_key_url }}"
    validate_certs: no
  when: not use_local_gpg_key | bool
  
- name: Add Yandex Cloud repository
  apt_repository:
    repo: "deb [arch=amd64] https://mirror.yandex.ru/mirrors/packages.grafana.com/enterprise/deb stable main"
    state: present
    validate_certs: no

- name: install grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: wait for service up
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1
  
- name: change admin password for grafana gui
  shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: __command_admin
  changed_when: __command_admin.rc !=0