apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to nginx!</title>
    </head>
    <body>
        <h1>Hello, Kubernetes!</h1>
    </body>
    </html>